> He およびＨの核座標が， それぞれ (0, 0,0)， (0, 0, 1.4) （bohr単位） のとき，  HeH の基底状態 （1σ2 2σ1） に対する UHF波動関数とUHF エネルギーを求めよ． 基底  関数は STO-NG (N＝1, 2, 3, 4, 5, 6) のいずれかとして， 付録の HeH 系の分子積分  の値を用 い よ． SCF の収束判定は， エ ネ ル ギ ー に つ い て の み行い， 閾値は  0.0001 hartree とせよ． また， 得られた UHF波動関数を用いて Mulliken の電子密度  解析を行い， He およびＨ原子の電荷およびスピン密度を求めよ． 
> 
> 中井浩巳. 手で解く量子化学 I (p. 99). (Function). Kindle Edition. 

基底関数は、STO-6Gとする。

In [1]:
from types import MappingProxyType
from itertools import product

import numpy as np
from scipy.linalg import ishermitian

## 対象分子の設定

核電荷$Z_\mathrm{He}=2.0$, $Z_\mathrm{H}=1.0$, 核座標$\boldsymbol{R_\mathrm{He}}=(0.0, 0.0, 0.0)$, $\boldsymbol{R_\mathrm{H}}=(0.0, 0.0, 1.4)$より、核反発エネルギー

$$
V_\mathrm{nuc} = \sum_{A=1}^M \sum_{B>A}^M \frac{Z_A Z_B}{R_{AB}}   \tag{3.2}
$$

In [2]:
Z_He = 2.0
"""Heの核電荷"""
Z_H = 1.0
"""Hの核電荷"""

'Hの核電荷'

In [3]:
V_nuc = (Z_He * Z_H) / 1.4
"""核間のポテンシャルエネルギー"""
V_nuc

1.4285714285714286

In [4]:
N_alpha = 2
"""upスピンの電子数"""
N_beta = 1
"""downスピンの電子数"""

'downスピンの電子数'

## 正準直行化の実行

重なり積分 $\boldsymbol{S}$ は、核座標と基底関数にのみ依存し、電子数には依存しない。

In [5]:
S = np.array([[1.0, 0.56059], [0.56059, 1.0]])
"""重なり行列 (付録より)"""
S

array([[1.     , 0.56059],
       [0.56059, 1.     ]])

In [6]:
def unitary_diagonalization(arr: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """ユニタリ対角化関数

    Parameters
    ----------
    arr : np.ndarray
        対角化する行列

    Returns
    -------
    tuple[np.ndarray, np.ndarray]
        対角化された行列とユニタリ行列

    Raises
    ------
    ValueError
        エルミート行列でない場合
    """
    if ishermitian(arr, rtol=1e-05, atol=1e-08):
        # エルミート行列の固有ベクトル
        _, u = np.linalg.eigh(arr)

        # Uの随伴行列(共役転置)
        u_dagger = np.conjugate(u.T)

        # エルミート行列をユニタリ行列で対角化
        diag_matrix = u_dagger @ arr @ u

        # データ型を整数に変更して小さな誤差が入っている虚部を取り除く
        # 単位行列をかけて対角成分以外の要素の誤差を小さくする
        diag_matrix = diag_matrix.astype(np.float64) * np.identity(
            arr.shape[0], dtype=np.float64
        )

        return diag_matrix, u
    else:
        raise ValueError("The matrix is not Hermitian.")


s, U = unitary_diagonalization(S)
"""s: 固有値
U: 固有ベクトル"""
print(f"{s=}")
print(f"{U=}")

s=array([[ 0.43941,  0.     ],
       [-0.     ,  1.56059]])
U=array([[-0.70710678,  0.70710678],
       [ 0.70710678,  0.70710678]])


正準直交化の変換行列 $X$ は、

$$
X_\mathrm{can} = U s^{-\frac{1}{2}} \tag{4.36}
$$

In [7]:
# 行列を^(-1/2)する。'-' は逆行列の意味
def inverse_sqrt_matrix(arr: np.ndarray) -> np.ndarray:
    """行列の^(-1/2)を計算する関数

    Parameters
    ----------
    arr : np.ndarray
        ^(-1/2)を計算する行列

    Returns
    -------
    np.ndarray
        ^(-1/2)された行列
    """
    return np.linalg.inv(np.sqrt(arr))


inverse_sqrt_matrix(s)

array([[1.50856849, 0.        ],
       [0.        , 0.80048941]])

In [8]:
X = U @ inverse_sqrt_matrix(s)
"""正準直行化の変換行列"""
X

array([[-1.06671901,  0.56603149],
       [ 1.06671901,  0.56603149]])

## コアハミルトニアン行列の計算

核座標と基底関数のみに依存し、電子数には依存しない。

In [9]:
H = np.array([[-2.6444, -1.5118], [-1.5118, -1.7782]])
"""コアハミルトニアン行列 (付録より)"""
H

array([[-2.6444, -1.5118],
       [-1.5118, -1.7782]])

## 密度行列の初期値

### 1-4-1と同じ方法

コアハミルトニアン行列を使うパターン

直行化基底に対するコアハミルトン行列 $H'$ は、

$$
H'=X^T HX   \tag{4.2}
$$

In [10]:
H_prime = X.T @ H @ X
"""正準直交化基底に対するコアハミルトニアン行列"""
H_prime

array([[-1.59190733,  0.52300857],
       [ 0.52300857, -2.38570028]])

In [11]:
_, C_prime = unitary_diagonalization(H_prime)
"""正準直交化基底に対する分子軌道係数行列"""
C_prime

array([[-0.44468334, -0.89568785],
       [ 0.89568785, -0.44468334]])

In [12]:
C = X @ C_prime
"""分子軌道係数行列"""
C

array([[ 0.9813397 ,  0.70374249],
       [ 0.03263536, -1.20715203]])

密度行列 $\boldsymbol{P}$ は、$\alpha$スピン、$\beta$スピンそれぞれに対して、

$$
P_{\mu\nu}^\alpha = 2 \sum_{i} {c_{\mu i}^\alpha}^* c_{\nu i}^\alpha \ ,\  P_{\mu\nu}^\beta = 2 \sum_{i} {c_{\mu i}^\beta}^* c_{\nu i}^\beta \tag{5.19}
$$

$i$は、分子軌道の足、$\mu, \nu$は原子軌道の足

HeH では、$N_\alpha=2, N_\beta=1$より、

$$
\begin{align*}
    P_{\mu \nu}^\alpha &= 2 \left(c_{\mu 1}^\alpha c_{\nu 1}^\alpha + c_{\mu 2}^\alpha c_{\nu 2}^\alpha \right) \\
    P_{\mu \nu}^\beta &= 2 c_{\mu 1}^\beta c_{\nu 1}^\beta
\end{align*}
$$

In [13]:
def calculate_density_matrix_alpha(C: np.ndarray) -> np.ndarray:
    """密度行列を計算する関数

    Parameters
    ----------
    C : np.ndarray
        分子軌道係数行列

    Returns
    -------
    np.ndarray
        密度行列
    """
    return C @ C.T  # 1-4-1と違って2を掛けないのは閉殻でないから。


P_alpha = calculate_density_matrix_alpha(C)
"""密度行列"""
P_alpha

array([[ 1.45828109, -0.8174978 ],
       [-0.8174978 ,  1.45828109]])

In [14]:
def calculate_density_matrix_beta(C: np.ndarray) -> np.ndarray:
    """密度行列を計算する関数

    Parameters
    ----------
    C : np.ndarray
        分子軌道係数行列

    Returns
    -------
    np.ndarray
        密度行列
    """
    return (
        C[:, [0]] @ C[:, [0]].T
    )  # 1-4-1と違って2を掛けないのは閉殻でないから。


P_beta = calculate_density_matrix_beta(C)
"""密度行列"""
P_beta

array([[0.9630276 , 0.03202637],
       [0.03202637, 0.00106507]])

## 電子反発積分の計算

In [15]:
MAP_ELECTRON_REPULSION_INTEGRAL = MappingProxyType(
    {
        ((1, 1), (1, 1)): 1.05625,
        ((1, 1), (1, 2)): 0.46768,
        ((1, 1), (2, 1)): 0.46768,
        ((1, 1), (2, 2)): 0.60640,
        ((1, 2), (1, 1)): 0.46768,
        ((1, 2), (1, 2)): 0.24649,
        ((1, 2), (2, 1)): 0.24649,
        ((1, 2), (2, 2)): 0.38871,
        ((2, 1), (1, 1)): 0.46768,
        ((2, 1), (1, 2)): 0.24649,
        ((2, 1), (2, 1)): 0.24649,
        ((2, 1), (2, 2)): 0.38871,
        ((2, 2), (1, 1)): 0.60640,
        ((2, 2), (1, 2)): 0.38871,
        ((2, 2), (2, 1)): 0.38871,
        ((2, 2), (2, 2)): 0.77500,
    }
)
"""電子反発積分 (付録より)"""
None

## Fock行列の計算

$$
F_{\mu \nu}^\alpha = H_{\mu \nu} + G_{\mu \nu}^\alpha  \\
F_{\mu \nu}^\beta = H_{\mu \nu} + G_{\mu \nu}^\beta \tag{5.26}
$$

$H_{\mu \nu}$ は、[先ほど](#コアハミルトニアン行列の計算)求めているので、$G_{\mu \nu}^\alpha, G_{\mu \nu}^\beta$ を求めたい。

$$
\begin{align*}
    J_{\mu \nu}^\alpha = \sum_{\lambda, \sigma} (\mu \nu | \lambda \sigma) P_{\lambda \sigma}^\alpha \ &,\ J_{\mu \nu}^\beta = \sum_{\lambda, \sigma} (\mu \nu | \lambda \sigma) P_{\lambda \sigma}^\beta \tag{5.21} \\
    K_{\mu \nu}^\alpha = \sum_{\lambda, \sigma} (\mu \sigma | \lambda \nu) P_{\lambda \sigma}^\alpha \ &,\ K_{\mu \nu}^\beta = \sum_{\lambda, \sigma} (\mu \sigma | \lambda \nu) P_{\lambda \sigma}^\beta \tag{5.22} \\
    G_{\mu \nu}^\alpha = J_{\mu \nu}^\alpha - K_{\mu \nu}^\alpha + J_{\mu \nu}^\beta \ &,\ G_{\mu \nu}^\beta = J_{\mu \nu}^\beta - K_{\mu \nu}^\beta + J_{\mu \nu}^\alpha \tag{5.23} \\
\end{align*}
$$

In [16]:
def calculate_coulomb_energy_matrix(P: np.ndarray) -> np.ndarray:
    """クーロンエネルギー行列を計算する関数

    Parameters
    ----------
    P : np.ndarray
        密度行列

    Returns
    -------
    np.ndarray
        クーロンエネルギー行列
    """
    return np.array(
        [
            [
                sum(
                    MAP_ELECTRON_REPULSION_INTEGRAL[
                        (_mu, _nu), (_lambda, _sigma)
                    ]
                    * P[_lambda - 1, _sigma - 1]  # Pは0-indexedなので-1する
                    for _lambda, _sigma in product((1, 2), repeat=2)
                )
                for _nu in (1, 2)
            ]
            for _mu in (1, 2)
        ]
    )

In [17]:
J_alpha = calculate_coulomb_energy_matrix(P_alpha)
"""クーロンエネルギー行列"""
J_alpha

array([[1.65995631, 0.84584728],
       [0.84584728, 1.37893036]])

In [18]:
J_beta = calculate_coulomb_energy_matrix(P_beta)
"""クーロンエネルギー行列"""
J_beta

array([[1.04779995, 0.46659111],
       [0.46659111, 0.60970331]])

In [19]:
def calculate_exchange_energy_matrix(P: np.ndarray) -> np.ndarray:
    """交換エネルギー行列を計算する関数

    Parameters
    ----------
    P : np.ndarray
        密度行列

    Returns
    -------
    np.ndarray
        交換エネルギー行列
    """
    return np.array(
        [
            [
                sum(
                    MAP_ELECTRON_REPULSION_INTEGRAL[
                        (_mu, _sigma), (_lambda, _nu)
                    ]
                    * P[_lambda - 1, _sigma - 1]  # Pは0-indexedなので-1する
                    for _lambda, _sigma in product((1, 2), repeat=2)
                )
                for _nu in (1, 2)
            ]
            for _mu in (1, 2)
        ]
    )

In [20]:
K_alpha = calculate_exchange_energy_matrix(P_alpha)
"""交換エネルギー行列"""
K_alpha

array([[1.13510637, 0.55162165],
       [0.55162165, 0.85408041]])

In [21]:
K_beta = calculate_exchange_energy_matrix(P_beta)
"""交換エネルギー行列"""
K_beta

array([[1.04741662, 0.47811773],
       [0.47811773, 0.26310004]])

In [22]:
G_alpha = J_alpha - K_alpha + J_beta
"""2電子積分行列"""
G_alpha

array([[1.5726499 , 0.76081675],
       [0.76081675, 1.13455326]])

In [23]:
G_beta = J_beta - K_beta + J_alpha
"""2電子積分行列"""
G_beta

array([[1.66033964, 0.83432067],
       [0.83432067, 1.72553363]])

In [24]:
F_alpha = H + G_alpha
"""Fock行列"""
F_alpha

array([[-1.0717501 , -0.75098325],
       [-0.75098325, -0.64364674]])

In [25]:
F_beta = H + G_beta
"""Fock行列"""
F_beta

array([[-0.98406036, -0.67747933],
       [-0.67747933, -0.05266637]])

In [26]:
def density2fock(
    P_alpha: np.ndarray, P_beta: np.ndarray
) -> tuple[np.ndarray, np.ndarray]:
    """密度行列からFock行列を計算する関数

    Parameters
    ----------
    P_alpha : np.ndarray
        upスピンの密度行列
    P_beta : np.ndarray
        downスピンの密度行列

    Returns
    -------
    tuple[np.ndarray, np.ndarray]
        upスピンとdownスピンのFock行列
    """
    J_alpha = calculate_coulomb_energy_matrix(P_alpha)
    K_alpha = calculate_exchange_energy_matrix(P_alpha)
    J_beta = calculate_coulomb_energy_matrix(P_beta)
    K_beta = calculate_exchange_energy_matrix(P_beta)

    G_alpha = J_alpha - K_alpha + J_beta
    G_beta = J_beta - K_beta + J_alpha
    return H + G_alpha, H + G_beta

In [27]:
density2fock(P_alpha, P_beta)

(array([[-1.0717501 , -0.75098325],
        [-0.75098325, -0.64364674]]),
 array([[-0.98406036, -0.67747933],
        [-0.67747933, -0.05266637]]))

## RHFエネルギーの計算

$$
E_0^\mathrm{UHF} = \frac{1}{2} \sum_{\mu,\nu} P_{\mu \nu}^\alpha \left[ H_{\mu \nu} + F_{\mu \nu}^\alpha \right] + \frac{1}{2} \sum_{\mu,\nu} P_{\mu \nu}^\beta \left[ H_{\mu \nu} + F_{\mu \nu}^\beta \right]  \tag{5.27}
$$

In [28]:
E_0 = 0.5 * np.sum(P_alpha * (H + F_alpha)) + 0.5 * np.sum(
    P_beta * (H + F_beta)
)
"""ハミルトニアンに対するRHFエネルギー"""
E_0

-4.443885456554934

In [29]:
E_tot = E_0 + V_nuc
"""RHF全エネルギー"""
E_tot

-3.0153140279835053

In [30]:
def calculate_total_energy(P_alpha: np.ndarray, P_beta: np.ndarray) -> float:
    """全エネルギーを計算する関数

    Parameters
    ----------
    P_alpha : np.ndarray
        upスピンの密度行列
    P_beta : np.ndarray
        downスピンの密度行列

    Returns
    -------
    float
        全エネルギー
    """
    F_alpha, F_beta = density2fock(P_alpha, P_beta)
    return (
        0.5 * np.sum(P_alpha * (H + F_alpha))
        + 0.5 * np.sum(P_beta * (H + F_beta))
        + V_nuc
    )

In [31]:
calculate_total_energy(P_alpha, P_beta)

-3.0153140279835053

## Pople-Nesbet方程式の解法

基本的には[Fock行列を求める](#fock行列の計算)から[RHFエネルギーの計算](#rhfエネルギーの計算)までを繰り返して、収束要件を満たしたら終わり。

In [32]:
def scf_cycle(
    P_alpha: np.ndarray, P_beta: np.ndarray, threshold: float = 1e-4
) -> tuple[float, tuple[np.ndarray, np.ndarray]]:
    """SCFサイクルを行う関数

    Parameters
    ----------
    P_alpha : np.ndarray
        upスピンの密度行列
    P_beta : np.ndarray
        downスピンの密度行列

    Returns
    -------
    tuple[float, tuple[np.ndarray, np.ndarray]]
        全エネルギーとupスピン、downスピンの密度行列
    """
    # 初期化
    E_tot_prev = np.inf
    # 全エネルギー
    E_tot = calculate_total_energy(P_alpha, P_beta)
    # 収束判定 (全エネルギーの変化量が閾値以下になるまで繰り返す)
    while (E_tot_prev - E_tot) > threshold:
        print(f"{E_tot=}")
        # 全エネルギーを保存
        E_tot_prev = E_tot
        # 密度行列からFock行列を計算
        F_alpha, F_beta = density2fock(P_alpha, P_beta)
        # 直交化基底に対するFock行列
        F_alpha_prime = X.T @ F_alpha @ X
        F_beta_prime = X.T @ F_beta @ X
        # Fock行列をユニタリ対角化して、(軌道エネルギーと) 分子軌道係数行列を求める
        _, C_alpha_prime = unitary_diagonalization(F_alpha_prime)
        _, C_beta_prime = unitary_diagonalization(F_beta_prime)
        # 分子軌道係数行列を元の基底に戻す
        C_alpha = X @ C_alpha_prime
        C_beta = X @ C_beta_prime
        # 密度行列を計算
        P_alpha = calculate_density_matrix_alpha(C_alpha)
        P_beta = calculate_density_matrix_beta(C_beta)
        # 全エネルギーを計算
        E_tot = calculate_total_energy(P_alpha, P_beta)
    return E_tot, (P_alpha, P_beta)

In [33]:
energy_total_opt, (P_alpha_opt, P_beta_opt) = scf_cycle(P_alpha, P_beta)
"""最適化された全エネルギーと密度行列"""
print(f"{energy_total_opt=}")
print(f"{P_alpha_opt=}")
print(f"{P_beta_opt=}")

E_tot=-3.0153140279835053
E_tot=-3.025361789251691
E_tot=-3.0264420000904924
E_tot=-3.026558145646497
energy_total_opt=-3.026570633908852
P_alpha_opt=array([[ 1.45828109, -0.8174978 ],
       [-0.8174978 ,  1.45828109]])
P_beta_opt=array([[0.81928634, 0.1398805 ],
       [0.1398805 , 0.02388244]])


## 分子物性の計算

Mullikenの電荷解析

$$
N_A^\mathrm{Mul} = \sum_{\mu \in A} \sum_{\nu} P_{\mu \nu} S_{\nu \mu} = \sum_{\mu \in A} (\rm{PS})_{\mu \mu} \tag{4.53}
$$

In [34]:
PS_alpha = P_alpha_opt @ S
"""upスピンの密度行列と重なり行列の積"""
PS_beta = P_beta_opt @ S
"""downスピンの密度行列と重なり行列の積"""

N_H_alpha = PS_alpha[0, 0]
"""upスピンのH原子の電子数"""
N_H_beta = PS_beta[0, 0]
"""downスピンのH原子の電子数"""
N_He_alpha = PS_alpha[1, 1]
"""upスピンのHe原子の電子数"""
N_He_beta = PS_beta[1, 1]
"""downスピンのHe原子の電子数"""

N_H = N_H_alpha + N_H_beta
"""H原子の電子数"""
N_He = N_He_alpha + N_He_beta
"""He原子の電子数"""

print(f"{N_H=}")
print(f"{N_He=}")

N_H=1.8977019511451552
N_He=1.1022980488548448


よって、Mulliken電荷は、
$$
Q_A = Z_A - N_A^\mathrm{mul} \tag{4.54}
$$
より、

In [35]:
Q_He = Z_He - N_He
"""Heの電荷"""
Q_H = Z_H - N_H
"""Hの電荷"""
print(f"{Q_He=}")
print(f"{Q_H=}")

Q_He=0.8977019511451552
Q_H=-0.8977019511451552


In [36]:
F_alpha_opt, F_beta_opt = density2fock(P_alpha_opt, P_beta_opt)

epsilon_alpha_opt, C_prime_alpha_opt = unitary_diagonalization(
    X.T @ F_alpha_opt @ X
)
epsilon_beta_opt, C_prime_beta_opt = unitary_diagonalization(
    X.T @ F_beta_opt @ X
)

C_alpha_opt = X @ C_prime_alpha_opt
C_beta_opt = X @ C_prime_beta_opt

print(f"{epsilon_alpha_opt=}")
print(f"{C_alpha_opt=}")
print(f"{epsilon_beta_opt=}")
print(f"{C_beta_opt=}")

epsilon_alpha_opt=array([[-1.13673078, -0.        ],
       [-0.        , -0.1616301 ]])
C_alpha_opt=array([[ 0.8711498 ,  0.83628889],
       [ 0.20416753, -1.19020868]])
epsilon_beta_opt=array([[-1.00238541, -0.        ],
       [-0.        ,  0.59822215]])
C_beta_opt=array([[ 0.90450872,  0.80009066],
       [ 0.15549133, -1.19754062]])


Koopmansの定理より、イオン化エネルギーおよび電子親和力は、

In [42]:
ionic_potential_energy = -epsilon_alpha_opt[1, 1]
"""イオン化ポテンシャルエネルギー"""
print(f"{ionic_potential_energy=} hartree")

ionic_potential_energy=0.16163009744793863 hartree


In [41]:
electron_affinity = -epsilon_beta_opt[1, 1]
"""電気陰性度"""
print(f"{electron_affinity=} hartree")

electron_affinity=-0.5982221462648253 hartree
